In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [2]:
data = pd.read_csv("data_zh.csv").values

In [27]:
data = np.delete(data, [4,5,28,29], 0)

In [7]:
x = data[:, 1:5]
x

array([[0.1892, 0.653, 41.0, 53.7],
       [0.1899, 0.6452, 41.0, 55.5],
       [0.2114, 0.6505, 41.6988, 57.6],
       ...,
       [0.2647, 0.6491, 39.0, 58.4],
       [0.2759, 0.6499, 39.0, 58.2],
       [0.131, 0.71, 44.3878, 56.3]], dtype=object)

In [8]:
y = data[:, 10] # 第15案
y

array([0.3484630163304515, 0.3181495617484033, 0.35719607599652303,
       0.3216651885857374, nan, nan, 0.3107075581518403,
       0.34171769748928355, 0.3191932723078068, 0.34543504901960786,
       0.2931893687707641, 0.3310340339688944, 0.3472709414901081,
       0.2999793260285301, 0.3297748123436197, 0.2325141776937618,
       0.2768278965129359, 0.31004179616332656, 0.1929107021131561,
       0.3317395290540462, 0.29946996466431103, 0.3494986245452125,
       0.3526808084182395, 0.34322831299702544, 0.3468157722750708,
       0.3400157232704403, 0.33863709418193505, 0.3174772848743987, nan,
       nan, 0.33148788927335643, 0.2098092643051771, 0.3115665161514415,
       0.34173848137341384, 0.3650523711977737, 0.387973086627418,
       0.3197847742310769, 0.3296906045983537, 0.3106393073182304,
       0.3246491497915584, 0.30110017371163866, 0.2722609766105868,
       0.2774349342634827, 0.2578604294478528, 0.2993496381789869,
       0.2822854305183877, 0.2474923680767553, 0.2929

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [14]:
x_train


array([[0.1254, 0.6319, 36.0, 58.4],
       [0.1789, 0.6613, 43.0, 54.6],
       [0.2042, 0.6566, 44.0, 59.8],
       [0.2087, 0.6391, 39.0, 69.8],
       [0.4236, 0.6654, 41.4738, 76.3],
       [0.1874, 0.6793, 45.0, 57.9],
       [0.1794, 0.6763, 41.0, 56.9],
       [0.1368, 0.7004, 44.7279, 56.4],
       [0.0914, 0.6515, 42.0, 58.8],
       [0.2026, 0.6409, 44.3246, 56.9],
       [0.1605, 0.6932, 46.3654, 57.6],
       [0.2684, 0.6363, 42.0, 61.3],
       [0.2472, 0.6517, 40.063, 59.9],
       [0.3398, 0.6642, 38.2985, 75.8],
       [0.2654, 0.6517, 42.0, 54.3],
       [0.0966, 0.6867, 47.0, 49.4],
       [0.3415, 0.6424, 39.0, 64.8],
       [0.1519, 0.7132, 49.0, 58.3],
       [0.2877, 0.6851, 41.1175, 72.0],
       [0.1128, 0.6759, 46.3125, 54.1],
       [0.2561, 0.665, 37.3284, 63.2],
       [0.3413, 0.645, 43.0, 61.6],
       [0.3194, 0.6629, 39.0, 67.8],
       [0.1653, 0.6785, 42.2467, 50.5],
       [0.1608, 0.6793, 44.0, 55.4],
       [0.1864, 0.6563, 44.5186, 56.2],
       [

In [15]:
y_train

array([0.2098092643051771, 0.3197847742310769, 0.3432405792706043,
       0.3100929614873838, 0.37715413017279104, 0.2845786963434022,
       0.33351780114370044, 0.3124321978737253, 0.2325015216068168,
       0.3463102559016068, 0.3001537279016141, 0.34191189314452736,
       0.3107075581518403, 0.3676496210471296, 0.3206963249516441,
       0.2931893687707641, 0.3474580482714066, 0.3013740458015267,
       0.2498334443704197, 0.3131772107654666, 0.3144877896890708,
       0.36253741318687693, 0.3482719331560957, 0.2903594927052541,
       0.34507993695113715, 0.32226608952100083, 0.3366940211019929,
       0.3169634370445472, 0.3488290807409997, 0.3215589934267313,
       0.2795199380565234, 0.25997045790251105, 0.3444584382871537,
       0.26464323748668794, 0.2048743335872049, 0.32713375796178346,
       0.34322831299702544, 0.3296906045983537, 0.3366851595006935,
       0.2880891844318404, 0.27541235136171843, 0.39554077452917263,
       0.31708410098092915, 0.3546503951562706, 0.